### ISSUE TITLE
room details by its position on a floor

### ISSUE THREAD

**Issue by diegocstn** [diegocstn/spazi-unimi-android-app#7]
As a user I want to look over the details of a room when I tap on it in a floor map

**Comment by khamusa** [comment]
Ma cazzo, non sono ancora soddisfatto di questa feature! Perché hai chiusa la issue, @diegocstn ?

:joy: :joy: :joy: :joy: 

Bei ricordi :)

**Comment by carlobellettini** [comment]
Era da segnare come wontfix ... Purtroppo...


Ciao Samuel

;-)



Il mar 21 apr 2020, 01:26 Samuel Brandão <notifications@github.com> ha
scritto:
